baseURL="https://livypad.github.io"
# disablePathToLower=True
languageCode = "zh"
title = "zhh's blog"
theme = "PaperModX"
paginate = 5

# [[menu.main]]
# identifier = "archive"
# name = "Archive"
# title = "Archive"
# url = "/posts/"
# weight = 0

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/archives/"
weight = 3

[[menu.main]]
name = "Note"
identifier = "note"
url = "/tags/读书笔记/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"

[author]
name = "livypad"

[params]
author = "livypad"
email = "ishonghua.zhu@outlook.com"
# description = "Welcome to zhh's blog"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
disableSummary= true
hidden = true
disableComments = true


defaultTheme="auto"
ShowBreadCrumbs=true
ShowReadingTime = true
ShowWordCount = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true
ShowPostNavLinks = true
TocSide="left"
[params.homeInfoParams]
Title = "Welcome to zhh's blog"
# Content = "Can be Info, links, about..."
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/livypad"
    [[params.socialIcons]]
    name = "email"
    url="ishonghua.zhu@outlook.com"
[params.assets]
    disableHLJS = true
[markup]
    [markup.highlight]
        codeFences= true
        guessSyntax = false
        noClasses= false
        # pygmentsUseClasses=false
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        # style = "manni"


